2024-04-11 10:29:09,251 INFO    StreamThr :6564 [internal.py:wandb_internal():86] W&B internal server running at pid: 6564, started at: 2024-04-11 10:29:09.250755
2024-04-11 10:29:09,252 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status
2024-04-11 10:29:09,256 INFO    WriterThread:6564 [datastore.py:open_for_write():87] open: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\run-zu3sexb2.wandb
2024-04-11 10:29:09,257 DEBUG   SenderThread:6564 [sender.py:send():379] send: header
2024-04-11 10:29:09,258 DEBUG   SenderThread:6564 [sender.py:send():379] send: run
2024-04-11 10:29:09,267 INFO    SenderThread:6564 [sender.py:_setup_resume():749] checking resume status for None/YOLOv5/zu3sexb2
2024-04-11 10:29:10,298 INFO    SenderThread:6564 [dir_watcher.py:__init__():211] watching files in: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files
2024-04-11 10:29:10,298 INFO    SenderThread:6564 [sender.py:_start_run_threads():1124] run started: zu3sexb2 with start time 1712802549.252716
2024-04-11 10:29:10,307 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: check_version
2024-04-11 10:29:10,307 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: check_version
2024-04-11 10:29:10,847 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: run_start
2024-04-11 10:29:10,875 DEBUG   HandlerThread:6564 [system_info.py:__init__():26] System info init
2024-04-11 10:29:10,875 DEBUG   HandlerThread:6564 [system_info.py:__init__():41] System info init done
2024-04-11 10:29:10,875 INFO    HandlerThread:6564 [system_monitor.py:start():194] Starting system monitor
2024-04-11 10:29:10,876 INFO    SystemMonitor:6564 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-04-11 10:29:10,876 INFO    HandlerThread:6564 [system_monitor.py:probe():214] Collecting system info
2024-04-11 10:29:10,879 INFO    SystemMonitor:6564 [interfaces.py:start():190] Started cpu monitoring
2024-04-11 10:29:10,880 INFO    SystemMonitor:6564 [interfaces.py:start():190] Started disk monitoring
2024-04-11 10:29:10,880 INFO    SystemMonitor:6564 [interfaces.py:start():190] Started gpu monitoring
2024-04-11 10:29:10,884 INFO    SystemMonitor:6564 [interfaces.py:start():190] Started memory monitoring
2024-04-11 10:29:10,893 INFO    SystemMonitor:6564 [interfaces.py:start():190] Started network monitoring
2024-04-11 10:29:10,894 DEBUG   HandlerThread:6564 [system_info.py:probe():150] Probing system
2024-04-11 10:29:10,896 DEBUG   HandlerThread:6564 [system_info.py:_probe_git():135] Probing git
2024-04-11 10:29:10,897 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:10,897 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:10,927 DEBUG   HandlerThread:6564 [system_info.py:_probe_git():143] Probing git done
2024-04-11 10:29:10,927 DEBUG   HandlerThread:6564 [system_info.py:probe():198] Probing system done
2024-04-11 10:29:10,927 DEBUG   HandlerThread:6564 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.19045-SP0', 'python': '3.10.14', 'heartbeatAt': '2024-04-11T02:29:10.895894', 'startedAt': '2024-04-11T02:29:09.244771', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'E:\\JD_PROJECT\\project\\ClassyVision\\train.py', 'codePathLocal': 'train.py', 'codePath': 'train.py', 'git': {'remote': None, 'commit': None}, 'email': None, 'root': 'E:/JD_PROJECT/project/ClassyVision', 'host': 'DZA-4CE139BDJQ', 'username': 'Administrator', 'executable': 'D:\\Users\\Administrator\\anaconda3\\envs\\ClassyVision2\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 2904.0, 'min': 0.0, 'max': 2904.0}, 'cpu_freq_per_core': [{'current': 2904.0, 'min': 0.0, 'max': 2904.0}], 'disk': {'/': {'total': 1745.8271446228027, 'used': 79.63630294799805}}, 'gpu': 'Quadro P1000', 'gpu_count': 1, 'gpu_devices': [{'name': 'Quadro P1000', 'memory_total': 4294967296}], 'memory': {'total': 31.781455993652344}}
2024-04-11 10:29:10,927 INFO    HandlerThread:6564 [system_monitor.py:probe():224] Finished collecting system info
2024-04-11 10:29:10,927 INFO    HandlerThread:6564 [system_monitor.py:probe():227] Publishing system info
2024-04-11 10:29:10,928 DEBUG   HandlerThread:6564 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-04-11 10:29:11,313 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_created():271] file/dir created: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\conda-environment.yaml
2024-04-11 10:29:12,918 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:12,918 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:14,940 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:14,940 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:16,950 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:16,950 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:18,976 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:18,976 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:19,266 DEBUG   HandlerThread:6564 [system_info.py:_save_conda():222] Saving conda packages done
2024-04-11 10:29:19,266 INFO    HandlerThread:6564 [system_monitor.py:probe():229] Finished publishing system info
2024-04-11 10:29:19,275 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:29:19,275 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: keepalive
2024-04-11 10:29:19,275 DEBUG   SenderThread:6564 [sender.py:send():379] send: files
2024-04-11 10:29:19,275 INFO    SenderThread:6564 [sender.py:_save_file():1390] saving file wandb-metadata.json with policy now
2024-04-11 10:29:19,371 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\conda-environment.yaml
2024-04-11 10:29:19,371 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_created():271] file/dir created: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\wandb-metadata.json
2024-04-11 10:29:19,518 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: python_packages
2024-04-11 10:29:19,518 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: python_packages
2024-04-11 10:29:19,519 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: stop_status
2024-04-11 10:29:19,519 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: stop_status
2024-04-11 10:29:19,520 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-11 10:29:19,997 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/wandb-metadata.json?Expires=1712888959&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=t4UA82D4voQADugkoL7jC1NpGdzGSQ9g5rlbq3tyyAVSxmrQsqwikFubk%2FnomkYOXFycr9GG58f89ngPlY1gSpLjY6rZh1rr8hIQRTPOQZdvPA8jT8nIuhDDvlCoUaoWlmy%2FPSA66wegeOE3IEgwXUsQLn8qeuIVb%2BcjTqgr4CI6%2BPz1MpsXCWmIXl%2BLzMeAYk5UWN5vgDMf61mrT0yhqRXgg7Z%2FHhsxbl8FCpUjwcbApswoKYsOVPbHnVGDplIlL667q1W%2FensWhaEX8DSXTwbZJJjVLW7pDDq0o5AuWXLVvlK6KQhSRmn5ylUEYhDIPudZm6eU62AcauJrlRzURA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:29:20,008 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1342'}
2024-04-11 10:29:20,008 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:29:20,022 DEBUG   SenderThread:6564 [sender.py:send():379] send: telemetry
2024-04-11 10:29:20,022 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:29:20,376 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_created():271] file/dir created: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\requirements.txt
2024-04-11 10:29:20,376 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_created():271] file/dir created: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:29:20,989 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:20,989 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:21,724 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/wandb-metadata.json?Expires=1712888959&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=t4UA82D4voQADugkoL7jC1NpGdzGSQ9g5rlbq3tyyAVSxmrQsqwikFubk%2FnomkYOXFycr9GG58f89ngPlY1gSpLjY6rZh1rr8hIQRTPOQZdvPA8jT8nIuhDDvlCoUaoWlmy%2FPSA66wegeOE3IEgwXUsQLn8qeuIVb%2BcjTqgr4CI6%2BPz1MpsXCWmIXl%2BLzMeAYk5UWN5vgDMf61mrT0yhqRXgg7Z%2FHhsxbl8FCpUjwcbApswoKYsOVPbHnVGDplIlL667q1W%2FensWhaEX8DSXTwbZJJjVLW7pDDq0o5AuWXLVvlK6KQhSRmn5ylUEYhDIPudZm6eU62AcauJrlRzURA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:29:21,724 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1342'}
2024-04-11 10:29:21,724 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:29:22,400 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:29:22,951 DEBUG   SenderThread:6564 [sender.py:send():379] send: files
2024-04-11 10:29:22,951 INFO    SenderThread:6564 [sender.py:_save_file():1390] saving file media\images\Labels_0_ef0dac86a8cda8f2dcbc.jpg with policy now
2024-04-11 10:29:22,956 DEBUG   SenderThread:6564 [sender.py:send():379] send: files
2024-04-11 10:29:22,956 INFO    SenderThread:6564 [sender.py:_save_file():1390] saving file media\images\Labels_0_a9f285194a601dcc1529.jpg with policy now
2024-04-11 10:29:22,973 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: partial_history
2024-04-11 10:29:23,005 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:23,005 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:23,407 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_created():271] file/dir created: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\media\images\Labels_0_ef0dac86a8cda8f2dcbc.jpg
2024-04-11 10:29:23,408 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_created():271] file/dir created: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\media\images\Labels_0_a9f285194a601dcc1529.jpg
2024-04-11 10:29:23,408 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_created():271] file/dir created: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\media
2024-04-11 10:29:23,409 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_created():271] file/dir created: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\media\images
2024-04-11 10:29:23,471 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Labels_0_ef0dac86a8cda8f2dcbc.jpg?Expires=1712888962&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PqrV2KCH61OeaeecwOtZnlRlJAjYbXq%2BHok4RMqMzPj7Rf9iGaSuzJLpw4e8Fl1GLMOnjQ9rO68dJNUkr%2Bfbf4llnSlmYK7TJuo2WeGU%2B8KCMKipbyTc2GBldEynuGKXKNtAz3uMPqhW76WEqLd9HLs%2FIBpWHH%2FKbY1ii0vp6EpFtVZcaNel2hknhPZKwpkDyhpQq7dt7Hz2312X0utkp4LlzrpnVyZ%2FFX9JsGeEC%2B3wXMiqYi%2Fxl0u9m4d31CVJTBIZzXuIo0%2FsYMcRMrEFxLPVKAyWPiqbrKkENuqONxmAeGQsk%2FKKBHxmbswOlaQhon%2B%2FVNdYir0brFUgtaM4OA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:29:23,472 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '102550'}
2024-04-11 10:29:23,472 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:29:23,477 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Labels_0_a9f285194a601dcc1529.jpg?Expires=1712888963&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cmps%2BsxoKLrxvFlc5fK1Pijb5HzDs1b3n9dj%2B9nuRGJw2Ibm4L8NGmwEUjc2yIbTfpLv9SBXh4U%2BG0hFNb8IDUqiDTZZNbc2sWaqyvK0BqHTuz5v19OxocXSTXrxPkMtBkzx9svyGKu5UG5SQG0EDbVPGKMu5sxZGZ%2FNfhi0%2BCNhf%2FGS9kVypC7o4TzhwZE09UgyhHU3w5j6RIyOMn9t7j1nF8k1noG3iC0e1%2Fz1xmBfnrLvf17dxrrpZpSXfZ4YaBZVAxhQuD1DzgRwfU77UWdiOcoJG72J4BYXVEtc61LyHY5fGlv5CSFBDuZjuWFF1hDfvEHC8HLRyaHPvJeJ%2BQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:29:23,477 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '155247'}
2024-04-11 10:29:23,477 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:29:24,342 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/wandb-metadata.json?Expires=1712888959&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=t4UA82D4voQADugkoL7jC1NpGdzGSQ9g5rlbq3tyyAVSxmrQsqwikFubk%2FnomkYOXFycr9GG58f89ngPlY1gSpLjY6rZh1rr8hIQRTPOQZdvPA8jT8nIuhDDvlCoUaoWlmy%2FPSA66wegeOE3IEgwXUsQLn8qeuIVb%2BcjTqgr4CI6%2BPz1MpsXCWmIXl%2BLzMeAYk5UWN5vgDMf61mrT0yhqRXgg7Z%2FHhsxbl8FCpUjwcbApswoKYsOVPbHnVGDplIlL667q1W%2FensWhaEX8DSXTwbZJJjVLW7pDDq0o5AuWXLVvlK6KQhSRmn5ylUEYhDIPudZm6eU62AcauJrlRzURA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:29:24,343 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1342'}
2024-04-11 10:29:24,343 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:29:24,418 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:29:24,975 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Labels_0_ef0dac86a8cda8f2dcbc.jpg?Expires=1712888962&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PqrV2KCH61OeaeecwOtZnlRlJAjYbXq%2BHok4RMqMzPj7Rf9iGaSuzJLpw4e8Fl1GLMOnjQ9rO68dJNUkr%2Bfbf4llnSlmYK7TJuo2WeGU%2B8KCMKipbyTc2GBldEynuGKXKNtAz3uMPqhW76WEqLd9HLs%2FIBpWHH%2FKbY1ii0vp6EpFtVZcaNel2hknhPZKwpkDyhpQq7dt7Hz2312X0utkp4LlzrpnVyZ%2FFX9JsGeEC%2B3wXMiqYi%2Fxl0u9m4d31CVJTBIZzXuIo0%2FsYMcRMrEFxLPVKAyWPiqbrKkENuqONxmAeGQsk%2FKKBHxmbswOlaQhon%2B%2FVNdYir0brFUgtaM4OA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:29:24,977 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '102550'}
2024-04-11 10:29:24,977 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:29:24,993 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Labels_0_a9f285194a601dcc1529.jpg?Expires=1712888963&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cmps%2BsxoKLrxvFlc5fK1Pijb5HzDs1b3n9dj%2B9nuRGJw2Ibm4L8NGmwEUjc2yIbTfpLv9SBXh4U%2BG0hFNb8IDUqiDTZZNbc2sWaqyvK0BqHTuz5v19OxocXSTXrxPkMtBkzx9svyGKu5UG5SQG0EDbVPGKMu5sxZGZ%2FNfhi0%2BCNhf%2FGS9kVypC7o4TzhwZE09UgyhHU3w5j6RIyOMn9t7j1nF8k1noG3iC0e1%2Fz1xmBfnrLvf17dxrrpZpSXfZ4YaBZVAxhQuD1DzgRwfU77UWdiOcoJG72J4BYXVEtc61LyHY5fGlv5CSFBDuZjuWFF1hDfvEHC8HLRyaHPvJeJ%2BQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:29:24,993 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '155247'}
2024-04-11 10:29:24,993 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:29:25,027 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:25,027 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:25,065 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:29:27,036 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:27,036 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:27,325 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Labels_0_ef0dac86a8cda8f2dcbc.jpg?Expires=1712888962&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PqrV2KCH61OeaeecwOtZnlRlJAjYbXq%2BHok4RMqMzPj7Rf9iGaSuzJLpw4e8Fl1GLMOnjQ9rO68dJNUkr%2Bfbf4llnSlmYK7TJuo2WeGU%2B8KCMKipbyTc2GBldEynuGKXKNtAz3uMPqhW76WEqLd9HLs%2FIBpWHH%2FKbY1ii0vp6EpFtVZcaNel2hknhPZKwpkDyhpQq7dt7Hz2312X0utkp4LlzrpnVyZ%2FFX9JsGeEC%2B3wXMiqYi%2Fxl0u9m4d31CVJTBIZzXuIo0%2FsYMcRMrEFxLPVKAyWPiqbrKkENuqONxmAeGQsk%2FKKBHxmbswOlaQhon%2B%2FVNdYir0brFUgtaM4OA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:29:27,325 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '102550'}
2024-04-11 10:29:27,325 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:29:27,412 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Labels_0_a9f285194a601dcc1529.jpg?Expires=1712888963&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cmps%2BsxoKLrxvFlc5fK1Pijb5HzDs1b3n9dj%2B9nuRGJw2Ibm4L8NGmwEUjc2yIbTfpLv9SBXh4U%2BG0hFNb8IDUqiDTZZNbc2sWaqyvK0BqHTuz5v19OxocXSTXrxPkMtBkzx9svyGKu5UG5SQG0EDbVPGKMu5sxZGZ%2FNfhi0%2BCNhf%2FGS9kVypC7o4TzhwZE09UgyhHU3w5j6RIyOMn9t7j1nF8k1noG3iC0e1%2Fz1xmBfnrLvf17dxrrpZpSXfZ4YaBZVAxhQuD1DzgRwfU77UWdiOcoJG72J4BYXVEtc61LyHY5fGlv5CSFBDuZjuWFF1hDfvEHC8HLRyaHPvJeJ%2BQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:29:27,413 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '155247'}
2024-04-11 10:29:27,413 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:29:29,058 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:29,058 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:29,560 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/wandb-metadata.json?Expires=1712888959&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=t4UA82D4voQADugkoL7jC1NpGdzGSQ9g5rlbq3tyyAVSxmrQsqwikFubk%2FnomkYOXFycr9GG58f89ngPlY1gSpLjY6rZh1rr8hIQRTPOQZdvPA8jT8nIuhDDvlCoUaoWlmy%2FPSA66wegeOE3IEgwXUsQLn8qeuIVb%2BcjTqgr4CI6%2BPz1MpsXCWmIXl%2BLzMeAYk5UWN5vgDMf61mrT0yhqRXgg7Z%2FHhsxbl8FCpUjwcbApswoKYsOVPbHnVGDplIlL667q1W%2FensWhaEX8DSXTwbZJJjVLW7pDDq0o5AuWXLVvlK6KQhSRmn5ylUEYhDIPudZm6eU62AcauJrlRzURA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:29:29,560 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1342'}
2024-04-11 10:29:29,560 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:29:30,101 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:29:31,075 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:31,075 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:32,152 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Labels_0_a9f285194a601dcc1529.jpg?Expires=1712888963&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cmps%2BsxoKLrxvFlc5fK1Pijb5HzDs1b3n9dj%2B9nuRGJw2Ibm4L8NGmwEUjc2yIbTfpLv9SBXh4U%2BG0hFNb8IDUqiDTZZNbc2sWaqyvK0BqHTuz5v19OxocXSTXrxPkMtBkzx9svyGKu5UG5SQG0EDbVPGKMu5sxZGZ%2FNfhi0%2BCNhf%2FGS9kVypC7o4TzhwZE09UgyhHU3w5j6RIyOMn9t7j1nF8k1noG3iC0e1%2Fz1xmBfnrLvf17dxrrpZpSXfZ4YaBZVAxhQuD1DzgRwfU77UWdiOcoJG72J4BYXVEtc61LyHY5fGlv5CSFBDuZjuWFF1hDfvEHC8HLRyaHPvJeJ%2BQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:29:32,152 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '155247'}
2024-04-11 10:29:32,152 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:29:32,319 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Labels_0_ef0dac86a8cda8f2dcbc.jpg?Expires=1712888962&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PqrV2KCH61OeaeecwOtZnlRlJAjYbXq%2BHok4RMqMzPj7Rf9iGaSuzJLpw4e8Fl1GLMOnjQ9rO68dJNUkr%2Bfbf4llnSlmYK7TJuo2WeGU%2B8KCMKipbyTc2GBldEynuGKXKNtAz3uMPqhW76WEqLd9HLs%2FIBpWHH%2FKbY1ii0vp6EpFtVZcaNel2hknhPZKwpkDyhpQq7dt7Hz2312X0utkp4LlzrpnVyZ%2FFX9JsGeEC%2B3wXMiqYi%2Fxl0u9m4d31CVJTBIZzXuIo0%2FsYMcRMrEFxLPVKAyWPiqbrKkENuqONxmAeGQsk%2FKKBHxmbswOlaQhon%2B%2FVNdYir0brFUgtaM4OA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:29:32,319 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '102550'}
2024-04-11 10:29:32,319 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:29:33,096 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:33,096 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:34,527 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-11 10:29:34,528 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: stop_status
2024-04-11 10:29:34,528 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: stop_status
2024-04-11 10:29:35,119 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:35,119 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:35,813 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:29:37,135 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:37,135 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:38,675 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/wandb-metadata.json?Expires=1712888959&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=t4UA82D4voQADugkoL7jC1NpGdzGSQ9g5rlbq3tyyAVSxmrQsqwikFubk%2FnomkYOXFycr9GG58f89ngPlY1gSpLjY6rZh1rr8hIQRTPOQZdvPA8jT8nIuhDDvlCoUaoWlmy%2FPSA66wegeOE3IEgwXUsQLn8qeuIVb%2BcjTqgr4CI6%2BPz1MpsXCWmIXl%2BLzMeAYk5UWN5vgDMf61mrT0yhqRXgg7Z%2FHhsxbl8FCpUjwcbApswoKYsOVPbHnVGDplIlL667q1W%2FensWhaEX8DSXTwbZJJjVLW7pDDq0o5AuWXLVvlK6KQhSRmn5ylUEYhDIPudZm6eU62AcauJrlRzURA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:29:38,675 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1342'}
2024-04-11 10:29:38,675 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:29:39,151 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:39,151 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:40,854 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:29:41,179 ERROR   gpu       :6564 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-04-11 10:29:41,180 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:41,180 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:41,572 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\config.yaml
2024-04-11 10:29:42,498 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Labels_0_ef0dac86a8cda8f2dcbc.jpg?Expires=1712888962&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PqrV2KCH61OeaeecwOtZnlRlJAjYbXq%2BHok4RMqMzPj7Rf9iGaSuzJLpw4e8Fl1GLMOnjQ9rO68dJNUkr%2Bfbf4llnSlmYK7TJuo2WeGU%2B8KCMKipbyTc2GBldEynuGKXKNtAz3uMPqhW76WEqLd9HLs%2FIBpWHH%2FKbY1ii0vp6EpFtVZcaNel2hknhPZKwpkDyhpQq7dt7Hz2312X0utkp4LlzrpnVyZ%2FFX9JsGeEC%2B3wXMiqYi%2Fxl0u9m4d31CVJTBIZzXuIo0%2FsYMcRMrEFxLPVKAyWPiqbrKkENuqONxmAeGQsk%2FKKBHxmbswOlaQhon%2B%2FVNdYir0brFUgtaM4OA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:29:42,498 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '102550'}
2024-04-11 10:29:42,498 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:29:43,189 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:43,189 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:45,206 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:45,206 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:46,165 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:29:47,209 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:47,209 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:49,218 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:49,218 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:49,518 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: stop_status
2024-04-11 10:29:49,518 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: stop_status
2024-04-11 10:29:49,534 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-11 10:29:51,231 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:51,231 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:51,828 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:29:53,250 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:53,250 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:55,264 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:55,264 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:56,700 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:29:56,952 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:29:56,961 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Labels_0_a9f285194a601dcc1529.jpg?Expires=1712888963&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cmps%2BsxoKLrxvFlc5fK1Pijb5HzDs1b3n9dj%2B9nuRGJw2Ibm4L8NGmwEUjc2yIbTfpLv9SBXh4U%2BG0hFNb8IDUqiDTZZNbc2sWaqyvK0BqHTuz5v19OxocXSTXrxPkMtBkzx9svyGKu5UG5SQG0EDbVPGKMu5sxZGZ%2FNfhi0%2BCNhf%2FGS9kVypC7o4TzhwZE09UgyhHU3w5j6RIyOMn9t7j1nF8k1noG3iC0e1%2Fz1xmBfnrLvf17dxrrpZpSXfZ4YaBZVAxhQuD1DzgRwfU77UWdiOcoJG72J4BYXVEtc61LyHY5fGlv5CSFBDuZjuWFF1hDfvEHC8HLRyaHPvJeJ%2BQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:29:56,962 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '155247'}
2024-04-11 10:29:56,962 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:29:57,281 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:57,281 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:58,717 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:29:58,732 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/wandb-metadata.json?Expires=1712888959&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=t4UA82D4voQADugkoL7jC1NpGdzGSQ9g5rlbq3tyyAVSxmrQsqwikFubk%2FnomkYOXFycr9GG58f89ngPlY1gSpLjY6rZh1rr8hIQRTPOQZdvPA8jT8nIuhDDvlCoUaoWlmy%2FPSA66wegeOE3IEgwXUsQLn8qeuIVb%2BcjTqgr4CI6%2BPz1MpsXCWmIXl%2BLzMeAYk5UWN5vgDMf61mrT0yhqRXgg7Z%2FHhsxbl8FCpUjwcbApswoKYsOVPbHnVGDplIlL667q1W%2FensWhaEX8DSXTwbZJJjVLW7pDDq0o5AuWXLVvlK6KQhSRmn5ylUEYhDIPudZm6eU62AcauJrlRzURA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:29:58,732 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1342'}
2024-04-11 10:29:58,732 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:29:59,300 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:29:59,301 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:00,755 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:01,315 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:01,315 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:02,051 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:30:02,164 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Labels_0_ef0dac86a8cda8f2dcbc.jpg?Expires=1712888962&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PqrV2KCH61OeaeecwOtZnlRlJAjYbXq%2BHok4RMqMzPj7Rf9iGaSuzJLpw4e8Fl1GLMOnjQ9rO68dJNUkr%2Bfbf4llnSlmYK7TJuo2WeGU%2B8KCMKipbyTc2GBldEynuGKXKNtAz3uMPqhW76WEqLd9HLs%2FIBpWHH%2FKbY1ii0vp6EpFtVZcaNel2hknhPZKwpkDyhpQq7dt7Hz2312X0utkp4LlzrpnVyZ%2FFX9JsGeEC%2B3wXMiqYi%2Fxl0u9m4d31CVJTBIZzXuIo0%2FsYMcRMrEFxLPVKAyWPiqbrKkENuqONxmAeGQsk%2FKKBHxmbswOlaQhon%2B%2FVNdYir0brFUgtaM4OA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:02,164 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '102550'}
2024-04-11 10:30:02,164 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:02,772 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:03,328 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:03,328 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:04,538 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: stop_status
2024-04-11 10:30:04,538 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-11 10:30:04,539 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: stop_status
2024-04-11 10:30:04,787 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:05,339 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:05,339 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:06,811 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:07,120 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:30:07,352 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:07,352 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:08,404 DEBUG   SenderThread:6564 [sender.py:send():379] send: files
2024-04-11 10:30:08,404 INFO    SenderThread:6564 [sender.py:_save_file():1390] saving file media\images\Mosaics_0_a2dca698d1e3c180b3af.jpg with policy now
2024-04-11 10:30:08,409 DEBUG   SenderThread:6564 [sender.py:send():379] send: files
2024-04-11 10:30:08,409 INFO    SenderThread:6564 [sender.py:_save_file():1390] saving file media\images\Mosaics_0_8f13a5d3bba7eb9fb38e.jpg with policy now
2024-04-11 10:30:08,413 DEBUG   SenderThread:6564 [sender.py:send():379] send: files
2024-04-11 10:30:08,413 INFO    SenderThread:6564 [sender.py:_save_file():1390] saving file media\images\Mosaics_0_4b69b9bea988ba2115e6.jpg with policy now
2024-04-11 10:30:08,432 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: partial_history
2024-04-11 10:30:08,830 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:08,831 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_created():271] file/dir created: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\media\images\Mosaics_0_8f13a5d3bba7eb9fb38e.jpg
2024-04-11 10:30:08,832 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_created():271] file/dir created: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\media\images\Mosaics_0_4b69b9bea988ba2115e6.jpg
2024-04-11 10:30:08,832 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_created():271] file/dir created: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\media\images\Mosaics_0_a2dca698d1e3c180b3af.jpg
2024-04-11 10:30:08,833 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\media\images
2024-04-11 10:30:09,059 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_a2dca698d1e3c180b3af.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=gUQALTsqxMTMTZ2l%2FiNSfN6BBGwi3nGr%2BlarozqiRuk2muPWVmGehUFIeNcnd4L1FEYC33nG%2BDBA5kO%2FEoFrbQBEChMPGmQn429beeA7ZeHnMQ5g5h4AcV6ebVkVQBIjGImiCN2W2kzvlN6k129Nm%2BKydPn9uVDB8DKK82iyZpfMAJ9i5mS5AbyoaASOC75Gcc%2B2%2F7xm%2BgFiSI%2FlMzXn9EV1j0EG04N4a7AWqAgMV10PVzrkcbQ8IZTNlYorn2bH%2FS%2BrgIY3ZVX9xUQ%2FViAGB9Zy%2FRb7JTD3%2BChPNDHKiuvoON2EHigQvaDGh8eJR9zy4tU4heWiYEVAeVJTPVCrzQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:09,059 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '259268'}
2024-04-11 10:30:09,059 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:09,167 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_8f13a5d3bba7eb9fb38e.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WYGiiOvSYQImPqMAKQpvKNqGVFoLDrt1tLh1tjAE1a37%2BQMqzRCThR6TjZz61OBq9o87yypt1stiTVIPRy42xav9UpLWydhHC0e%2Frmq%2Fm3rJ2lJRCHP5R%2FHmqD0N7YO62aGi8h%2Fw6zemrTAC%2FWShS1TJFFAnbUMhRplElu0G%2B71Zg5dbjIs3imAZRHVjG5X%2F5f2JRF38CD6OZ8tsC5goTWfomQbx7ECe2LG7yOgWiShlGxaAg8If13pe9ukL31MDK9gAVfOJXaaprx2LV9RzQNcwx%2BeYqtlIJEMbJPjXjL5REWGi%2BtAYE8d0lw2m5S54KF2FseUqbiGBMQJDyg9AdQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:09,168 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '252067'}
2024-04-11 10:30:09,168 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:09,293 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_4b69b9bea988ba2115e6.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FMGv%2Bo0Mvwiw8kjpIQcljLhZ8JsrgOelXYDRqQ24qRHRv6K6NQAfayaVHdkcvqmRXVoAQ%2B6vQpN1QZQjScNcMSAgY43JlZwF34MkhYpbwt10aTnce5XkBGtU9MHArWfNKkMv7WL7r8w%2BYb4yI2nMo2jtdCbaMSdfZAlmLKi2Kvse73jdwClVZqEyr45ZNBa8m6SQVhi6Oy%2BYtcefY7GoBYfFEKYNXlEJ2MLonATk%2Be7%2BnsjFvDM9tT86Mpe9olggfd9qICE7gpoFZsv0MqX5BIL%2BjXn34%2FlZQuL%2FMMdzUepq3RRwmCLlWZctJpssagxTPFlDxQqE2GmsCR9NY2WQVg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:09,293 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '208053'}
2024-04-11 10:30:09,293 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:09,370 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:09,370 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:10,520 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_a2dca698d1e3c180b3af.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=gUQALTsqxMTMTZ2l%2FiNSfN6BBGwi3nGr%2BlarozqiRuk2muPWVmGehUFIeNcnd4L1FEYC33nG%2BDBA5kO%2FEoFrbQBEChMPGmQn429beeA7ZeHnMQ5g5h4AcV6ebVkVQBIjGImiCN2W2kzvlN6k129Nm%2BKydPn9uVDB8DKK82iyZpfMAJ9i5mS5AbyoaASOC75Gcc%2B2%2F7xm%2BgFiSI%2FlMzXn9EV1j0EG04N4a7AWqAgMV10PVzrkcbQ8IZTNlYorn2bH%2FS%2BrgIY3ZVX9xUQ%2FViAGB9Zy%2FRb7JTD3%2BChPNDHKiuvoON2EHigQvaDGh8eJR9zy4tU4heWiYEVAeVJTPVCrzQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:10,520 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '259268'}
2024-04-11 10:30:10,520 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:10,520 INFO    wandb-upload_3:6564 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\ssl.py", line 1104, in _create
    self.do_handshake()
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\ssl.py", line 1104, in _create
    self.do_handshake()
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2760, in upload_file
    response = self._upload_file_session.put(
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\requests\sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2791, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2760, in upload_file
    response = self._upload_file_session.put(
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\requests\sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Users\Administrator\anaconda3\envs\ClassyVision2\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-04-11 10:30:10,558 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_8f13a5d3bba7eb9fb38e.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WYGiiOvSYQImPqMAKQpvKNqGVFoLDrt1tLh1tjAE1a37%2BQMqzRCThR6TjZz61OBq9o87yypt1stiTVIPRy42xav9UpLWydhHC0e%2Frmq%2Fm3rJ2lJRCHP5R%2FHmqD0N7YO62aGi8h%2Fw6zemrTAC%2FWShS1TJFFAnbUMhRplElu0G%2B71Zg5dbjIs3imAZRHVjG5X%2F5f2JRF38CD6OZ8tsC5goTWfomQbx7ECe2LG7yOgWiShlGxaAg8If13pe9ukL31MDK9gAVfOJXaaprx2LV9RzQNcwx%2BeYqtlIJEMbJPjXjL5REWGi%2BtAYE8d0lw2m5S54KF2FseUqbiGBMQJDyg9AdQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:10,558 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '252067'}
2024-04-11 10:30:10,558 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:10,756 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_4b69b9bea988ba2115e6.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FMGv%2Bo0Mvwiw8kjpIQcljLhZ8JsrgOelXYDRqQ24qRHRv6K6NQAfayaVHdkcvqmRXVoAQ%2B6vQpN1QZQjScNcMSAgY43JlZwF34MkhYpbwt10aTnce5XkBGtU9MHArWfNKkMv7WL7r8w%2BYb4yI2nMo2jtdCbaMSdfZAlmLKi2Kvse73jdwClVZqEyr45ZNBa8m6SQVhi6Oy%2BYtcefY7GoBYfFEKYNXlEJ2MLonATk%2Be7%2BnsjFvDM9tT86Mpe9olggfd9qICE7gpoFZsv0MqX5BIL%2BjXn34%2FlZQuL%2FMMdzUepq3RRwmCLlWZctJpssagxTPFlDxQqE2GmsCR9NY2WQVg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:10,756 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '208053'}
2024-04-11 10:30:10,756 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:10,845 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:10,892 DEBUG   SystemMonitor:6564 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-04-11 10:30:10,892 DEBUG   SenderThread:6564 [sender.py:send():379] send: stats
2024-04-11 10:30:11,412 ERROR   gpu       :6564 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-04-11 10:30:11,413 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:11,413 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:12,277 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:30:12,865 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:13,068 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_4b69b9bea988ba2115e6.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FMGv%2Bo0Mvwiw8kjpIQcljLhZ8JsrgOelXYDRqQ24qRHRv6K6NQAfayaVHdkcvqmRXVoAQ%2B6vQpN1QZQjScNcMSAgY43JlZwF34MkhYpbwt10aTnce5XkBGtU9MHArWfNKkMv7WL7r8w%2BYb4yI2nMo2jtdCbaMSdfZAlmLKi2Kvse73jdwClVZqEyr45ZNBa8m6SQVhi6Oy%2BYtcefY7GoBYfFEKYNXlEJ2MLonATk%2Be7%2BnsjFvDM9tT86Mpe9olggfd9qICE7gpoFZsv0MqX5BIL%2BjXn34%2FlZQuL%2FMMdzUepq3RRwmCLlWZctJpssagxTPFlDxQqE2GmsCR9NY2WQVg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:13,068 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '208053'}
2024-04-11 10:30:13,068 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:13,225 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_a2dca698d1e3c180b3af.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=gUQALTsqxMTMTZ2l%2FiNSfN6BBGwi3nGr%2BlarozqiRuk2muPWVmGehUFIeNcnd4L1FEYC33nG%2BDBA5kO%2FEoFrbQBEChMPGmQn429beeA7ZeHnMQ5g5h4AcV6ebVkVQBIjGImiCN2W2kzvlN6k129Nm%2BKydPn9uVDB8DKK82iyZpfMAJ9i5mS5AbyoaASOC75Gcc%2B2%2F7xm%2BgFiSI%2FlMzXn9EV1j0EG04N4a7AWqAgMV10PVzrkcbQ8IZTNlYorn2bH%2FS%2BrgIY3ZVX9xUQ%2FViAGB9Zy%2FRb7JTD3%2BChPNDHKiuvoON2EHigQvaDGh8eJR9zy4tU4heWiYEVAeVJTPVCrzQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:13,225 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '259268'}
2024-04-11 10:30:13,225 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:13,291 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_8f13a5d3bba7eb9fb38e.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WYGiiOvSYQImPqMAKQpvKNqGVFoLDrt1tLh1tjAE1a37%2BQMqzRCThR6TjZz61OBq9o87yypt1stiTVIPRy42xav9UpLWydhHC0e%2Frmq%2Fm3rJ2lJRCHP5R%2FHmqD0N7YO62aGi8h%2Fw6zemrTAC%2FWShS1TJFFAnbUMhRplElu0G%2B71Zg5dbjIs3imAZRHVjG5X%2F5f2JRF38CD6OZ8tsC5goTWfomQbx7ECe2LG7yOgWiShlGxaAg8If13pe9ukL31MDK9gAVfOJXaaprx2LV9RzQNcwx%2BeYqtlIJEMbJPjXjL5REWGi%2BtAYE8d0lw2m5S54KF2FseUqbiGBMQJDyg9AdQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:13,291 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '252067'}
2024-04-11 10:30:13,291 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:13,429 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:13,429 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:14,866 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:15,444 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:15,444 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:16,454 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Labels_0_a9f285194a601dcc1529.jpg?Expires=1712888963&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cmps%2BsxoKLrxvFlc5fK1Pijb5HzDs1b3n9dj%2B9nuRGJw2Ibm4L8NGmwEUjc2yIbTfpLv9SBXh4U%2BG0hFNb8IDUqiDTZZNbc2sWaqyvK0BqHTuz5v19OxocXSTXrxPkMtBkzx9svyGKu5UG5SQG0EDbVPGKMu5sxZGZ%2FNfhi0%2BCNhf%2FGS9kVypC7o4TzhwZE09UgyhHU3w5j6RIyOMn9t7j1nF8k1noG3iC0e1%2Fz1xmBfnrLvf17dxrrpZpSXfZ4YaBZVAxhQuD1DzgRwfU77UWdiOcoJG72J4BYXVEtc61LyHY5fGlv5CSFBDuZjuWFF1hDfvEHC8HLRyaHPvJeJ%2BQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:16,454 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '155247'}
2024-04-11 10:30:16,454 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:16,896 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:17,459 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:17,459 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:17,538 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:30:17,778 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_a2dca698d1e3c180b3af.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=gUQALTsqxMTMTZ2l%2FiNSfN6BBGwi3nGr%2BlarozqiRuk2muPWVmGehUFIeNcnd4L1FEYC33nG%2BDBA5kO%2FEoFrbQBEChMPGmQn429beeA7ZeHnMQ5g5h4AcV6ebVkVQBIjGImiCN2W2kzvlN6k129Nm%2BKydPn9uVDB8DKK82iyZpfMAJ9i5mS5AbyoaASOC75Gcc%2B2%2F7xm%2BgFiSI%2FlMzXn9EV1j0EG04N4a7AWqAgMV10PVzrkcbQ8IZTNlYorn2bH%2FS%2BrgIY3ZVX9xUQ%2FViAGB9Zy%2FRb7JTD3%2BChPNDHKiuvoON2EHigQvaDGh8eJR9zy4tU4heWiYEVAeVJTPVCrzQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:17,778 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '259268'}
2024-04-11 10:30:17,778 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:18,001 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_8f13a5d3bba7eb9fb38e.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WYGiiOvSYQImPqMAKQpvKNqGVFoLDrt1tLh1tjAE1a37%2BQMqzRCThR6TjZz61OBq9o87yypt1stiTVIPRy42xav9UpLWydhHC0e%2Frmq%2Fm3rJ2lJRCHP5R%2FHmqD0N7YO62aGi8h%2Fw6zemrTAC%2FWShS1TJFFAnbUMhRplElu0G%2B71Zg5dbjIs3imAZRHVjG5X%2F5f2JRF38CD6OZ8tsC5goTWfomQbx7ECe2LG7yOgWiShlGxaAg8If13pe9ukL31MDK9gAVfOJXaaprx2LV9RzQNcwx%2BeYqtlIJEMbJPjXjL5REWGi%2BtAYE8d0lw2m5S54KF2FseUqbiGBMQJDyg9AdQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:18,001 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '252067'}
2024-04-11 10:30:18,001 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:18,113 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_4b69b9bea988ba2115e6.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FMGv%2Bo0Mvwiw8kjpIQcljLhZ8JsrgOelXYDRqQ24qRHRv6K6NQAfayaVHdkcvqmRXVoAQ%2B6vQpN1QZQjScNcMSAgY43JlZwF34MkhYpbwt10aTnce5XkBGtU9MHArWfNKkMv7WL7r8w%2BYb4yI2nMo2jtdCbaMSdfZAlmLKi2Kvse73jdwClVZqEyr45ZNBa8m6SQVhi6Oy%2BYtcefY7GoBYfFEKYNXlEJ2MLonATk%2Be7%2BnsjFvDM9tT86Mpe9olggfd9qICE7gpoFZsv0MqX5BIL%2BjXn34%2FlZQuL%2FMMdzUepq3RRwmCLlWZctJpssagxTPFlDxQqE2GmsCR9NY2WQVg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:18,113 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '208053'}
2024-04-11 10:30:18,113 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:18,920 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:19,469 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:19,469 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:19,530 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: stop_status
2024-04-11 10:30:19,530 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: stop_status
2024-04-11 10:30:19,546 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-11 10:30:20,941 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:21,474 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:21,474 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:22,726 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:30:22,957 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:23,489 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:23,489 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:24,984 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:25,502 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:25,502 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:26,519 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_a2dca698d1e3c180b3af.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=gUQALTsqxMTMTZ2l%2FiNSfN6BBGwi3nGr%2BlarozqiRuk2muPWVmGehUFIeNcnd4L1FEYC33nG%2BDBA5kO%2FEoFrbQBEChMPGmQn429beeA7ZeHnMQ5g5h4AcV6ebVkVQBIjGImiCN2W2kzvlN6k129Nm%2BKydPn9uVDB8DKK82iyZpfMAJ9i5mS5AbyoaASOC75Gcc%2B2%2F7xm%2BgFiSI%2FlMzXn9EV1j0EG04N4a7AWqAgMV10PVzrkcbQ8IZTNlYorn2bH%2FS%2BrgIY3ZVX9xUQ%2FViAGB9Zy%2FRb7JTD3%2BChPNDHKiuvoON2EHigQvaDGh8eJR9zy4tU4heWiYEVAeVJTPVCrzQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:26,519 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '259268'}
2024-04-11 10:30:26,519 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:27,006 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:27,510 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:27,510 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:27,644 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_4b69b9bea988ba2115e6.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FMGv%2Bo0Mvwiw8kjpIQcljLhZ8JsrgOelXYDRqQ24qRHRv6K6NQAfayaVHdkcvqmRXVoAQ%2B6vQpN1QZQjScNcMSAgY43JlZwF34MkhYpbwt10aTnce5XkBGtU9MHArWfNKkMv7WL7r8w%2BYb4yI2nMo2jtdCbaMSdfZAlmLKi2Kvse73jdwClVZqEyr45ZNBa8m6SQVhi6Oy%2BYtcefY7GoBYfFEKYNXlEJ2MLonATk%2Be7%2BnsjFvDM9tT86Mpe9olggfd9qICE7gpoFZsv0MqX5BIL%2BjXn34%2FlZQuL%2FMMdzUepq3RRwmCLlWZctJpssagxTPFlDxQqE2GmsCR9NY2WQVg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:27,644 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '208053'}
2024-04-11 10:30:27,645 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:27,754 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_8f13a5d3bba7eb9fb38e.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WYGiiOvSYQImPqMAKQpvKNqGVFoLDrt1tLh1tjAE1a37%2BQMqzRCThR6TjZz61OBq9o87yypt1stiTVIPRy42xav9UpLWydhHC0e%2Frmq%2Fm3rJ2lJRCHP5R%2FHmqD0N7YO62aGi8h%2Fw6zemrTAC%2FWShS1TJFFAnbUMhRplElu0G%2B71Zg5dbjIs3imAZRHVjG5X%2F5f2JRF38CD6OZ8tsC5goTWfomQbx7ECe2LG7yOgWiShlGxaAg8If13pe9ukL31MDK9gAVfOJXaaprx2LV9RzQNcwx%2BeYqtlIJEMbJPjXjL5REWGi%2BtAYE8d0lw2m5S54KF2FseUqbiGBMQJDyg9AdQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:27,755 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '252067'}
2024-04-11 10:30:27,755 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:27,983 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:30:29,021 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:29,530 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:29,531 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:31,035 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:31,542 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:31,542 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:33,049 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:33,230 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:30:33,556 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:33,556 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:34,469 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Labels_0_ef0dac86a8cda8f2dcbc.jpg?Expires=1712888962&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PqrV2KCH61OeaeecwOtZnlRlJAjYbXq%2BHok4RMqMzPj7Rf9iGaSuzJLpw4e8Fl1GLMOnjQ9rO68dJNUkr%2Bfbf4llnSlmYK7TJuo2WeGU%2B8KCMKipbyTc2GBldEynuGKXKNtAz3uMPqhW76WEqLd9HLs%2FIBpWHH%2FKbY1ii0vp6EpFtVZcaNel2hknhPZKwpkDyhpQq7dt7Hz2312X0utkp4LlzrpnVyZ%2FFX9JsGeEC%2B3wXMiqYi%2Fxl0u9m4d31CVJTBIZzXuIo0%2FsYMcRMrEFxLPVKAyWPiqbrKkENuqONxmAeGQsk%2FKKBHxmbswOlaQhon%2B%2FVNdYir0brFUgtaM4OA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:34,469 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '102550'}
2024-04-11 10:30:34,469 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:34,531 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: stop_status
2024-04-11 10:30:34,531 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: stop_status
2024-04-11 10:30:34,547 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-11 10:30:35,063 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:35,574 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:35,574 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:37,071 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:37,591 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:37,591 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:38,348 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/wandb-metadata.json?Expires=1712888959&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=t4UA82D4voQADugkoL7jC1NpGdzGSQ9g5rlbq3tyyAVSxmrQsqwikFubk%2FnomkYOXFycr9GG58f89ngPlY1gSpLjY6rZh1rr8hIQRTPOQZdvPA8jT8nIuhDDvlCoUaoWlmy%2FPSA66wegeOE3IEgwXUsQLn8qeuIVb%2BcjTqgr4CI6%2BPz1MpsXCWmIXl%2BLzMeAYk5UWN5vgDMf61mrT0yhqRXgg7Z%2FHhsxbl8FCpUjwcbApswoKYsOVPbHnVGDplIlL667q1W%2FensWhaEX8DSXTwbZJJjVLW7pDDq0o5AuWXLVvlK6KQhSRmn5ylUEYhDIPudZm6eU62AcauJrlRzURA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:38,348 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1342'}
2024-04-11 10:30:38,348 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:38,431 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:30:39,097 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:39,607 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:39,607 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:40,900 DEBUG   SenderThread:6564 [sender.py:send():379] send: stats
2024-04-11 10:30:41,103 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:41,656 ERROR   gpu       :6564 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-04-11 10:30:41,657 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:41,657 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:43,131 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:43,395 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_a2dca698d1e3c180b3af.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=gUQALTsqxMTMTZ2l%2FiNSfN6BBGwi3nGr%2BlarozqiRuk2muPWVmGehUFIeNcnd4L1FEYC33nG%2BDBA5kO%2FEoFrbQBEChMPGmQn429beeA7ZeHnMQ5g5h4AcV6ebVkVQBIjGImiCN2W2kzvlN6k129Nm%2BKydPn9uVDB8DKK82iyZpfMAJ9i5mS5AbyoaASOC75Gcc%2B2%2F7xm%2BgFiSI%2FlMzXn9EV1j0EG04N4a7AWqAgMV10PVzrkcbQ8IZTNlYorn2bH%2FS%2BrgIY3ZVX9xUQ%2FViAGB9Zy%2FRb7JTD3%2BChPNDHKiuvoON2EHigQvaDGh8eJR9zy4tU4heWiYEVAeVJTPVCrzQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:43,395 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '259268'}
2024-04-11 10:30:43,395 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:43,662 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:43,662 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:43,669 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:30:45,141 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:30:45,672 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:45,672 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:46,415 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_4b69b9bea988ba2115e6.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FMGv%2Bo0Mvwiw8kjpIQcljLhZ8JsrgOelXYDRqQ24qRHRv6K6NQAfayaVHdkcvqmRXVoAQ%2B6vQpN1QZQjScNcMSAgY43JlZwF34MkhYpbwt10aTnce5XkBGtU9MHArWfNKkMv7WL7r8w%2BYb4yI2nMo2jtdCbaMSdfZAlmLKi2Kvse73jdwClVZqEyr45ZNBa8m6SQVhi6Oy%2BYtcefY7GoBYfFEKYNXlEJ2MLonATk%2Be7%2BnsjFvDM9tT86Mpe9olggfd9qICE7gpoFZsv0MqX5BIL%2BjXn34%2FlZQuL%2FMMdzUepq3RRwmCLlWZctJpssagxTPFlDxQqE2GmsCR9NY2WQVg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:46,415 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '208053'}
2024-04-11 10:30:46,415 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:47,675 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:47,675 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:48,122 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_8f13a5d3bba7eb9fb38e.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WYGiiOvSYQImPqMAKQpvKNqGVFoLDrt1tLh1tjAE1a37%2BQMqzRCThR6TjZz61OBq9o87yypt1stiTVIPRy42xav9UpLWydhHC0e%2Frmq%2Fm3rJ2lJRCHP5R%2FHmqD0N7YO62aGi8h%2Fw6zemrTAC%2FWShS1TJFFAnbUMhRplElu0G%2B71Zg5dbjIs3imAZRHVjG5X%2F5f2JRF38CD6OZ8tsC5goTWfomQbx7ECe2LG7yOgWiShlGxaAg8If13pe9ukL31MDK9gAVfOJXaaprx2LV9RzQNcwx%2BeYqtlIJEMbJPjXjL5REWGi%2BtAYE8d0lw2m5S54KF2FseUqbiGBMQJDyg9AdQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:48,122 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '252067'}
2024-04-11 10:30:48,122 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:48,702 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:30:49,545 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: stop_status
2024-04-11 10:30:49,545 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: stop_status
2024-04-11 10:30:49,561 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-11 10:30:49,686 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:49,686 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:51,696 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:51,696 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:53,707 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:53,707 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:53,849 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:30:55,718 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:55,718 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:55,981 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Labels_0_a9f285194a601dcc1529.jpg?Expires=1712888963&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=cmps%2BsxoKLrxvFlc5fK1Pijb5HzDs1b3n9dj%2B9nuRGJw2Ibm4L8NGmwEUjc2yIbTfpLv9SBXh4U%2BG0hFNb8IDUqiDTZZNbc2sWaqyvK0BqHTuz5v19OxocXSTXrxPkMtBkzx9svyGKu5UG5SQG0EDbVPGKMu5sxZGZ%2FNfhi0%2BCNhf%2FGS9kVypC7o4TzhwZE09UgyhHU3w5j6RIyOMn9t7j1nF8k1noG3iC0e1%2Fz1xmBfnrLvf17dxrrpZpSXfZ4YaBZVAxhQuD1DzgRwfU77UWdiOcoJG72J4BYXVEtc61LyHY5fGlv5CSFBDuZjuWFF1hDfvEHC8HLRyaHPvJeJ%2BQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:30:55,982 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '155247'}
2024-04-11 10:30:55,982 ERROR   wandb-upload_2:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:30:57,735 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:57,735 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:58,899 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:30:59,746 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:30:59,747 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:01,761 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:01,761 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:03,775 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:03,775 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:03,937 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:31:04,547 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: stop_status
2024-04-11 10:31:04,548 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: stop_status
2024-04-11 10:31:04,563 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-11 10:31:05,795 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:05,795 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:07,806 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:07,806 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:09,822 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:09,822 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:09,906 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:31:10,904 DEBUG   SenderThread:6564 [sender.py:send():379] send: stats
2024-04-11 10:31:11,855 ERROR   gpu       :6564 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-04-11 10:31:11,856 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:11,856 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:13,861 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:13,861 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:15,070 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:31:15,388 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:31:15,872 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:15,872 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:17,889 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:17,890 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:19,554 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: stop_status
2024-04-11 10:31:19,554 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: stop_status
2024-04-11 10:31:19,569 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-11 10:31:19,903 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:19,904 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:20,804 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:31:21,921 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:21,921 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:22,248 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_a2dca698d1e3c180b3af.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=gUQALTsqxMTMTZ2l%2FiNSfN6BBGwi3nGr%2BlarozqiRuk2muPWVmGehUFIeNcnd4L1FEYC33nG%2BDBA5kO%2FEoFrbQBEChMPGmQn429beeA7ZeHnMQ5g5h4AcV6ebVkVQBIjGImiCN2W2kzvlN6k129Nm%2BKydPn9uVDB8DKK82iyZpfMAJ9i5mS5AbyoaASOC75Gcc%2B2%2F7xm%2BgFiSI%2FlMzXn9EV1j0EG04N4a7AWqAgMV10PVzrkcbQ8IZTNlYorn2bH%2FS%2BrgIY3ZVX9xUQ%2FViAGB9Zy%2FRb7JTD3%2BChPNDHKiuvoON2EHigQvaDGh8eJR9zy4tU4heWiYEVAeVJTPVCrzQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:31:22,248 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '259268'}
2024-04-11 10:31:22,248 ERROR   wandb-upload_3:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:31:23,459 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:31:23,935 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:23,935 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:24,098 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_4b69b9bea988ba2115e6.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FMGv%2Bo0Mvwiw8kjpIQcljLhZ8JsrgOelXYDRqQ24qRHRv6K6NQAfayaVHdkcvqmRXVoAQ%2B6vQpN1QZQjScNcMSAgY43JlZwF34MkhYpbwt10aTnce5XkBGtU9MHArWfNKkMv7WL7r8w%2BYb4yI2nMo2jtdCbaMSdfZAlmLKi2Kvse73jdwClVZqEyr45ZNBa8m6SQVhi6Oy%2BYtcefY7GoBYfFEKYNXlEJ2MLonATk%2Be7%2BnsjFvDM9tT86Mpe9olggfd9qICE7gpoFZsv0MqX5BIL%2BjXn34%2FlZQuL%2FMMdzUepq3RRwmCLlWZctJpssagxTPFlDxQqE2GmsCR9NY2WQVg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:31:24,098 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '208053'}
2024-04-11 10:31:24,098 ERROR   wandb-upload_5:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:31:25,471 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:31:25,947 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:25,947 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:26,259 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Mosaics_0_8f13a5d3bba7eb9fb38e.jpg?Expires=1712889008&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WYGiiOvSYQImPqMAKQpvKNqGVFoLDrt1tLh1tjAE1a37%2BQMqzRCThR6TjZz61OBq9o87yypt1stiTVIPRy42xav9UpLWydhHC0e%2Frmq%2Fm3rJ2lJRCHP5R%2FHmqD0N7YO62aGi8h%2Fw6zemrTAC%2FWShS1TJFFAnbUMhRplElu0G%2B71Zg5dbjIs3imAZRHVjG5X%2F5f2JRF38CD6OZ8tsC5goTWfomQbx7ECe2LG7yOgWiShlGxaAg8If13pe9ukL31MDK9gAVfOJXaaprx2LV9RzQNcwx%2BeYqtlIJEMbJPjXjL5REWGi%2BtAYE8d0lw2m5S54KF2FseUqbiGBMQJDyg9AdQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:31:26,259 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '252067'}
2024-04-11 10:31:26,259 ERROR   wandb-upload_4:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:31:26,609 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:31:27,493 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:31:27,968 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:27,968 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:29,523 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:31:29,990 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:29,990 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:31,543 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:31:32,012 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:32,020 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:31:32,107 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:33,570 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:31:34,114 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:34,114 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:34,553 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: stop_status
2024-04-11 10:31:34,553 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: stop_status
2024-04-11 10:31:34,584 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-11 10:31:35,597 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:31:36,116 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:36,117 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:37,611 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:31:37,800 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:31:38,128 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:38,128 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:39,628 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:31:40,142 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:40,142 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:40,907 DEBUG   SenderThread:6564 [sender.py:send():379] send: stats
2024-04-11 10:31:41,648 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:31:42,176 ERROR   gpu       :6564 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-04-11 10:31:42,177 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:42,177 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:42,965 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:31:43,668 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:31:44,184 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:44,184 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:45,539 DEBUG   SenderThread:6564 [sender.py:send():379] send: telemetry
2024-04-11 10:31:45,539 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: partial_history
2024-04-11 10:31:45,540 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: partial_history
2024-04-11 10:31:45,540 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: partial_history
2024-04-11 10:31:45,540 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: partial_history
2024-04-11 10:31:45,540 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: partial_history
2024-04-11 10:31:45,540 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: partial_history
2024-04-11 10:31:45,541 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: partial_history
2024-04-11 10:31:45,541 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: partial_history
2024-04-11 10:31:45,541 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: partial_history
2024-04-11 10:31:45,541 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: partial_history
2024-04-11 10:31:45,541 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: partial_history
2024-04-11 10:31:45,542 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: partial_history
2024-04-11 10:31:45,542 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: partial_history
2024-04-11 10:31:45,564 DEBUG   SenderThread:6564 [sender.py:send():379] send: history
2024-04-11 10:31:45,565 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: summary_record
2024-04-11 10:31:45,565 INFO    SenderThread:6564 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-04-11 10:31:45,678 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_created():271] file/dir created: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\wandb-summary.json
2024-04-11 10:31:46,194 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:46,194 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:47,690 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:31:48,207 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:48,207 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:48,349 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:31:48,693 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\config.yaml
2024-04-11 10:31:49,553 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: stop_status
2024-04-11 10:31:49,554 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: stop_status
2024-04-11 10:31:49,584 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-11 10:31:49,708 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:31:50,045 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/media/images/Labels_0_ef0dac86a8cda8f2dcbc.jpg?Expires=1712888962&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PqrV2KCH61OeaeecwOtZnlRlJAjYbXq%2BHok4RMqMzPj7Rf9iGaSuzJLpw4e8Fl1GLMOnjQ9rO68dJNUkr%2Bfbf4llnSlmYK7TJuo2WeGU%2B8KCMKipbyTc2GBldEynuGKXKNtAz3uMPqhW76WEqLd9HLs%2FIBpWHH%2FKbY1ii0vp6EpFtVZcaNel2hknhPZKwpkDyhpQq7dt7Hz2312X0utkp4LlzrpnVyZ%2FFX9JsGeEC%2B3wXMiqYi%2Fxl0u9m4d31CVJTBIZzXuIo0%2FsYMcRMrEFxLPVKAyWPiqbrKkENuqONxmAeGQsk%2FKKBHxmbswOlaQhon%2B%2FVNdYir0brFUgtaM4OA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:31:50,045 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '102550'}
2024-04-11 10:31:50,045 ERROR   wandb-upload_1:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:31:50,219 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:50,219 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:51,726 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:31:52,226 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:52,226 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:53,609 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:31:53,741 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:31:54,230 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:54,231 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:54,754 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:31:56,240 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:56,240 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:56,773 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:31:58,254 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:58,254 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:31:58,533 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/beallhuang/YOLOv5/zu3sexb2/wandb-metadata.json?Expires=1712888959&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=t4UA82D4voQADugkoL7jC1NpGdzGSQ9g5rlbq3tyyAVSxmrQsqwikFubk%2FnomkYOXFycr9GG58f89ngPlY1gSpLjY6rZh1rr8hIQRTPOQZdvPA8jT8nIuhDDvlCoUaoWlmy%2FPSA66wegeOE3IEgwXUsQLn8qeuIVb%2BcjTqgr4CI6%2BPz1MpsXCWmIXl%2BLzMeAYk5UWN5vgDMf61mrT0yhqRXgg7Z%2FHhsxbl8FCpUjwcbApswoKYsOVPbHnVGDplIlL667q1W%2FensWhaEX8DSXTwbZJJjVLW7pDDq0o5AuWXLVvlK6KQhSRmn5ylUEYhDIPudZm6eU62AcauJrlRzURA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-04-11 10:31:58,533 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1342'}
2024-04-11 10:31:58,533 ERROR   wandb-upload_0:6564 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-11 10:31:58,637 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:31:58,788 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:32:00,270 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:32:00,270 ERROR   gpu       :6564 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-04-11 10:32:00,813 INFO    Thread-16 :6564 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\JD_PROJECT\project\ClassyVision\wandb\run-20240411_102909-zu3sexb2\files\output.log
2024-04-11 10:32:01,213 DEBUG   SenderThread:6564 [sender.py:send():379] send: exit
2024-04-11 10:32:01,213 INFO    SenderThread:6564 [sender.py:send_exit():586] handling exit code: 255
2024-04-11 10:32:01,213 INFO    SenderThread:6564 [sender.py:send_exit():588] handling runtime: 170
2024-04-11 10:32:01,214 INFO    SenderThread:6564 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-04-11 10:32:01,214 INFO    SenderThread:6564 [sender.py:send_exit():594] send defer
2024-04-11 10:32:01,214 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: defer
2024-04-11 10:32:01,214 INFO    HandlerThread:6564 [handler.py:handle_request_defer():172] handle defer: 0
2024-04-11 10:32:01,214 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: defer
2024-04-11 10:32:01,214 INFO    SenderThread:6564 [sender.py:send_request_defer():610] handle sender defer: 0
2024-04-11 10:32:01,214 INFO    SenderThread:6564 [sender.py:transition_state():614] send defer: 1
2024-04-11 10:32:01,215 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: defer
2024-04-11 10:32:01,215 INFO    HandlerThread:6564 [handler.py:handle_request_defer():172] handle defer: 1
2024-04-11 10:32:01,215 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: defer
2024-04-11 10:32:01,215 INFO    SenderThread:6564 [sender.py:send_request_defer():610] handle sender defer: 1
2024-04-11 10:32:01,215 INFO    SenderThread:6564 [sender.py:transition_state():614] send defer: 2
2024-04-11 10:32:01,215 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: defer
2024-04-11 10:32:01,215 INFO    HandlerThread:6564 [handler.py:handle_request_defer():172] handle defer: 2
2024-04-11 10:32:01,215 INFO    HandlerThread:6564 [system_monitor.py:finish():203] Stopping system monitor
2024-04-11 10:32:01,215 DEBUG   SystemMonitor:6564 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-04-11 10:32:01,215 INFO    HandlerThread:6564 [interfaces.py:finish():202] Joined cpu monitor
2024-04-11 10:32:01,219 DEBUG   SystemMonitor:6564 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-04-11 10:32:01,219 INFO    HandlerThread:6564 [interfaces.py:finish():202] Joined disk monitor
2024-04-11 10:32:01,235 ERROR   gpu       :6564 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-04-11 10:32:01,235 INFO    HandlerThread:6564 [interfaces.py:finish():202] Joined gpu monitor
2024-04-11 10:32:01,235 INFO    HandlerThread:6564 [interfaces.py:finish():202] Joined memory monitor
2024-04-11 10:32:01,236 INFO    HandlerThread:6564 [interfaces.py:finish():202] Joined network monitor
2024-04-11 10:32:01,236 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: defer
2024-04-11 10:32:01,236 INFO    SenderThread:6564 [sender.py:send_request_defer():610] handle sender defer: 2
2024-04-11 10:32:01,236 INFO    SenderThread:6564 [sender.py:transition_state():614] send defer: 3
2024-04-11 10:32:01,236 DEBUG   SenderThread:6564 [sender.py:send():379] send: stats
2024-04-11 10:32:01,237 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: defer
2024-04-11 10:32:01,237 INFO    HandlerThread:6564 [handler.py:handle_request_defer():172] handle defer: 3
2024-04-11 10:32:01,237 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: defer
2024-04-11 10:32:01,237 INFO    SenderThread:6564 [sender.py:send_request_defer():610] handle sender defer: 3
2024-04-11 10:32:01,237 INFO    SenderThread:6564 [sender.py:transition_state():614] send defer: 4
2024-04-11 10:32:01,237 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: defer
2024-04-11 10:32:01,237 INFO    HandlerThread:6564 [handler.py:handle_request_defer():172] handle defer: 4
2024-04-11 10:32:01,237 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: defer
2024-04-11 10:32:01,237 INFO    SenderThread:6564 [sender.py:send_request_defer():610] handle sender defer: 4
2024-04-11 10:32:01,237 INFO    SenderThread:6564 [sender.py:transition_state():614] send defer: 5
2024-04-11 10:32:01,238 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: defer
2024-04-11 10:32:01,238 INFO    HandlerThread:6564 [handler.py:handle_request_defer():172] handle defer: 5
2024-04-11 10:32:01,238 DEBUG   SenderThread:6564 [sender.py:send():379] send: summary
2024-04-11 10:32:01,238 INFO    SenderThread:6564 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-04-11 10:32:01,239 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: defer
2024-04-11 10:32:01,239 INFO    SenderThread:6564 [sender.py:send_request_defer():610] handle sender defer: 5
2024-04-11 10:32:01,239 INFO    SenderThread:6564 [sender.py:transition_state():614] send defer: 6
2024-04-11 10:32:01,239 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: defer
2024-04-11 10:32:01,239 INFO    HandlerThread:6564 [handler.py:handle_request_defer():172] handle defer: 6
2024-04-11 10:32:01,239 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: defer
2024-04-11 10:32:01,239 INFO    SenderThread:6564 [sender.py:send_request_defer():610] handle sender defer: 6
2024-04-11 10:32:01,239 INFO    SenderThread:6564 [sender.py:transition_state():614] send defer: 7
2024-04-11 10:32:01,239 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: status_report
2024-04-11 10:32:01,239 DEBUG   HandlerThread:6564 [handler.py:handle_request():146] handle_request: defer
2024-04-11 10:32:01,239 INFO    HandlerThread:6564 [handler.py:handle_request_defer():172] handle defer: 7
2024-04-11 10:32:01,240 DEBUG   SenderThread:6564 [sender.py:send_request():406] send_request: defer
2024-04-11 10:32:01,240 INFO    SenderThread:6564 [sender.py:send_request_defer():610] handle sender defer: 7
